version: '3'
services:
    db:
        image: postgres
        container_name: post-postgres
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: postgres
